### ISSUE TITLE
如何配置xavs2参数可以输出30帧一个IDR的帧结构？

### ISSUE THREAD

**Issue by yaowangvrviu** [pkuvcl/xavs2#12]
1. 使用-f encoder_ldp.cfg可以达到期望的每30帧一个I帧。但是没有B帧；
2. 使用命令参数 --IntraPeriod=30 输出的结果在100帧里面只有首帧是I；
3. 使用命令参数 --NumberBFrames=0，输出还是有B帧，设置无效；
4. gop_size在AVS2里面是什么概念，看起来和h264的感念不一样，不能正确理解。
谢谢！

**Comment by luofalei** [comment]
最新版本已修正IntraPeriod问题，可通过
```
--IntraPeriodMax=30 --IntraPeriodMin=30 --OpenGOP=0
```
设置成想要的任意I帧间隔。
