### ISSUE TITLE
Build fails with gcc8

### ISSUE THREAD

**Issue by dbermond** [pkuvcl/xavs2#17]
**Describe the bug**

I'm getting the following error when trying to build xavs2 git master with gcc8:

- [https://bpaste.net/show/1e8824ef32b8](https://bpaste.net/show/1e8824ef32b8)

**To Reproduce**

The steps to reproduce are already described on the above link.

**Expected behavior**

A successful build with gcc8.

**Screenshots**

Not applicable.

**Desktop (please complete the following information):**
 - **OS:** Arch Linux x86_64
 - **Compiler:** gcc 8.2.1
 - **yasm:** 1.3.0
 - **glibc:** 2.28
 - **l-smash:** 2.14.5

**Additional context**

It builds fine when using gcc 7.3.1.

**Comment by luofalei** [comment]
Thanks for pointing out the bugs.
Could you help to figure out which intrinsic brings in the bug or fix this problem?

**Comment by dbermond** [comment]
@luofalei It looks like that `_mm256_insertf128_si256` and `_mm256_castsi128_si256` are undeclared in the scope of `source/common/vec/intrinsic.h`, which seems to be strictly not permitted by gcc8.

I have created a pull request that fixes this issue.

After applying the fix, xavs2 builds fine for me with the following gcc versions:

:heavy_check_mark: gcc 8.2.1
:heavy_check_mark: gcc 7.3.1
:heavy_check_mark: gcc 6.5.0
