### ISSUE TITLE
win32平台无法在Windows上编译

### ISSUE THREAD

**Issue by sonyps5201314** [pkuvcl/xavs2#3]
win32 release配置
..\..\source\common\x86\quant8.asm(216): error : invalid combination of opcode and operands

1>..\..\source\common\vec\intrinsic_cg_scan.c(138): warning C4013: “_mm_set_epi64x”未定义；假设外部返回 int
1>..\..\source\common\vec\intrinsic_cg_scan.c(138): error C2440: “=”: 无法从“int”转换为“__m128i”
1>..\..\source\common\vec\intrinsic_cg_scan.c(139): error C2440: “=”: 无法从“int”转换为“__m128i”
1>..\..\source\common\vec\intrinsic_cg_scan.c(168): error C2440: “=”: 无法从“int”转换为“__m128i”
1>..\..\source\common\vec\intrinsic_cg_scan.c(169): error C2440: “=”: 无法从“int”转换为“__m128i”

**Comment by luofalei** [comment]
@sonyps5201314 建议先使用x64配置

**Comment by sonyps5201314** [comment]
好的，只好这样了，希望能尽快支持x86 32位架构。
问一下，本avs2算法对屏幕录像有针对优化吗？我用x265录制孙鑫的c++视频教程 需要132M还不包含音频，但是原始的swf文件只有42M还包含音频。不知道本算法下压缩效果如何？

**Comment by luofalei** [comment]
@sonyps5201314 目前未针对屏幕视频进行针对性优化

**Comment by sonyps5201314** [comment]
好吧 谢谢了，希望有机会官方能增加这种长期静态或者只有局部在变化的视频进行优化。这样就更加适用于远程教学，远程会议，现场新闻直播传送等需要实时播放转播的情况了。当然更适合作为屏幕录像的首选格式。

**Comment by tnti** [comment]
看着像vsyasm没配置好...

**Comment by luofalei** [comment]
目前`Win32`/`x64`平台均可编译，本Issue将关闭。
