### ISSUE TITLE
在windows平台编译出错

### ISSUE THREAD

**Issue by weiystyle** [pkuvcl/xavs2#4]
错误	10	error LNK1181: 无法打开输入文件
“E:\DisNotEnough\forever\xavs2master\build\vs2013\x64\libxavs2.lib”
错误	9	error LNK1181: 无法打开输入文件“libxavs2asm.lib”
错误	1	error MSB3721: 命令“"D:\vs2013\vs2013_installation\VC\bin\"vsyasm.exe -Xvc -f x64 -d "HIGH_BIT_DEPTH=0" -d "BIT_DEPTH=8" -d "ARCH_X86_64=1" -o "x64\Release\libxavs2asm\\" -rnasm -pnasm   ..\..\source\common\x86\blockcopy8.asm  "..\..\source\common\x86\const-a.asm"  "..\..\source\common\x86\cpu-a.asm"  ..\..\source\common\x86\dct8.asm  "..\..\source\common\x86\mc-a.asm"  "..\..\source\common\x86\mc-a2.asm"  "..\..\source\common\x86\pixel-32.asm"  "..\..\source\common\x86\pixel-a.asm"  "..\..\source\common\x86\pixel-util8.asm"  ..\..\source\common\x86\pixeladd8.asm  ..\..\source\common\x86\quant8.asm  "..\..\source\common\x86\sad-a.asm"  "..\..\source\common\x86\satd-a.asm"  "..\..\source\common\x86\ssd-a.asm"  ..\..\source\common\x86\x86inc.asm  ..\..\source\common\x86\x86util.asm”已退出，返回代码为 -1073741515。

**Comment by luofalei** [comment]
看起来是这个vsyasm的路径不太对，少了一个斜杠。
```
D:\vs2013\vs2013_installation\VC\bin"vsyasm.exe
```

**Comment by weiystyle** [comment]
这个问题我已经解决了，你能看看我新提出的问题吗，谢谢了
