### ISSUE TITLE
具体参数调用方法？

### ISSUE THREAD

**Issue by weiystyle** [pkuvcl/xavs2#6]
README 中使用如下命令进行编码 ./xavs2 -f encoder.cfg -f seq4K.cfg -p InputFile=input.yuv -p FramesToBeEncoded=500 -p preset=0 -p recon=. -p initial_qp=32 -p OutputFile=test.avs
但是源码包中并没有encoder.cfg seq4K.cfg等配置文件，我把源码包中有的配置文件都尝试了一遍，会出现Failed to read one YUV frame这样的问题
如果不使用配置文件进行编码则编码不成功
顺便咨询一下这个编码是否是这样一个流程：
支持各种视频格式转换成avs文件，然后解码将avs文件转换成yuv文件

**Comment by luofalei** [comment]
（1）`config`目录下有一个 `seq-template.cfg` 文件，修改其中的YUV文件路径即可。
（2）目前只支持将YUV420p格式的视频文件转换成符合AVS2视频标准的码流文件，任意格式之间的转换可以尝试下 ffmpeg `https://github.com/pkuvcl/buildFFmpegAVS2`
